### ISSUE TITLE
Road map for development

### ISSUE THREAD

**Issue by aaa006bd** [geprog/dev-addy#2]
This issue addresses the general development plan for the dev-addy aka codecaptain.ai which is a tool that allows a user to interact with a code base and analyze and document in a conversational manner. Mentioned below are the areas that should be addressed:

### General

- [ ] Use database for tracking user chat
- [ ] Use separate storage for the code repos

### AI

- [ ] Use intelligent parsing of code files
- [ ] Investigate different embeddings( one we are using is the folder structure described as a text later used as an embedding)
- [ ] include PRs as embeddings
- [ ] include issue comments as embeddings
- [ ] include PR comments as embeddings
- [ ] Investigate system messages
- [ ] Update embeddings on commit/reindex with the changed codebase
- [ ] Investigate other generative models( custom/ open source)

### Back-end

- [ ] Standardize the api
- [ ] Endpoints for working with code repos from storage(CRUD)
- [ ] Endpoints for user informations(for profile settings)

### Front-end

- [ ] UI for general login(currently its login via github)
- [ ] UI for User profile(only some basic informations at this point)
- [ ] UI for adding code repos via URL(github, gitlab, bitbucket etc)
- [ ] UI for uploading code repos(some kind of drag drop or upload button)

**Comment by aaa006bd** [comment]
@anbraten please check and edit if needed.

**Comment by anbraten** [comment]
@aaa006bd Those are some nice ideas. But before we start engineering sth we should think about what nice functions codecaptian should provider for a user. Exp: #3 is about adding a database for chat-history, but how would that be beneficial for a user? Would it for example show old conversations, would it allow auto-completion using old text messages, ...?

**Comment by anbraten** [comment]
Some features I had in mind:
- Support for other forges in addition to Github
- The knowledge / emebeddings of the repo could be used to do automatic code-reviews.
- Send newletter-ish email / create an issue with things the AI suggests you to improve in your project. Somehow like an inspection by some expert consultant, maybe also sth like an security audit / automatic pen-test.
- Auto generated FAQs / Knowledge docs (auto generate system architecture diagram)

**Comment by anbraten** [comment]
- [ ] fix indexing
- [ ] chats
  - [ ] stored in db
  - [ ] open new chat for a configured repo
  - [ ] fork chat
  - [ ] summarize chat text and show as title
- [ ] orgs
  - [ ] share configured forge
  - [ ] share openai key
  - [ ] share chat
